#!/bin/sh

# Find all main JavaScript files generated by Vite and loop through them
find /usr/share/nginx/html/assets -name "*.js" | while read -r JS_FILE; do
  if [ -f "$JS_FILE" ]; then
    echo "Processing file: $JS_FILE"

    # Replace placeholders with environment variables
    # Note: We use a different delimiter for sed because the variables contain slashes
    sed -i "s|VITE_API_URL_PLACEHOLDER|${VITE_API_URL}|g" "$JS_FILE"
    sed -i "s|VITE_MAPBOX_ACCESS_TOKEN_PLACEHOLDER|${VITE_MAPBOX_ACCESS_TOKEN}|g" "$JS_FILE"
    sed -i "s|VITE_CLERK_PUBLISHABLE_KEY_PLACEHOLDER|${VITE_CLERK_PUBLISHABLE_KEY}|g" "$JS_FILE"
    sed -i "s|VITE_CLERK_SECRET_KEY_PLACEHOLDER|${VITE_CLERK_SECRET_KEY}|g" "$JS_FILE"
    sed -i "s|VITE_GOOGLEMAP_ACCESS_TOKEN_PLACEHOLDER|${VITE_GOOGLEMAP_ACCESS_TOKEN}|g" "$JS_FILE"
  fi
done

echo "Environment variables injected."

# Start Nginx in the foreground
nginx -g 'daemon off;'
